### ISSUE TITLE
Helix branch can't play HD channels

### ISSUE THREAD

**Issue by zz64** [pipelka/xbmc-addon-xvdr#149] opened 2015-03-18 16:17 UTC
Hi, i can't play HD channel with XVDR (Helix branch)
If I leave a few minutes I get a choppy video ):
is work fine with VNSI, but i don't need use this addons because i have a big list of channels, and VNSI is not able to load this big list..

here xvdr plugin log: http://pastebin.com/raw.php?i=E33BGeLa
xbmc log using xvdr :http://pastebin.com/raw.php?i=aCXhevyE

playing fine with VNSI xbmc log: http://pastebin.com/raw.php?i=ZYQjU6ND

useful information:
Kodi (14.1 Git:Unknown). Platform: Linux x86 32-bit
Running on Debian GNU/Linux 8 (jessie), kernel: Linux x86 32-bit version 3.19.0-atom-low-latency
FFmpeg statically linked, version: 2.4.6-xbmc-2.4.6-Helix
Host CPU: Intel(R) Celeron(R) CPU J1800 @ 2.41GHz, 2 cores available
plugin: xvdr (0.9.9)

any idea ?
or should use another branch ?

Thanks.

**Comment by zz64** [comment] 2015-03-18 16:35
it only applies to French channels
I have just tried, the german HD channels work fine like ZDF HD...

**Comment by pipelka** [comment] 2015-03-18 16:37
I'm assuming you are using the latest "kodi-helix" branch of the plugin.

Are you using timeshift (configuration)?
What's the cpu usage when the video starts to get choppy?
The logs are a bit short. Are there any messages when the problem starts?
Is this happening on any hd channel or just on this one?

Many things I want to know,...

**Comment by zz64** [comment] 2015-03-18 16:42
il applies to all French HD channels.
the cpu usage : vdr=102%  kodi=40%
i think is audio AC3 related.
500 lines of XVDR plugin log: http://pastebin.com/raw.php?i=1X1Yti2e

**Comment by zz64** [comment] 2015-03-18 16:56
Here short video dumped with VLC from vdr streamdev-server:
https://drive.google.com/file/d/0B40c_0M8n5IJMFNaYTNJMm1nZTQ/view?pli=1

**Comment by pipelka** [comment] 2015-03-18 18:56
Thanks for the information.

I just pushed the "ac3-fix" branch. This is a wild guess what may cause the problem.
Please check if this branch makes any difference for you.

**Comment by pipelka** [comment] 2015-03-18 18:57
Ehmm. The "ac3-fix" branch is in the vdr-plugin, ... 
I guess the problem is located in the vdr-plugin, not the kodi addon.

**Comment by zz64** [comment] 2015-03-18 21:09
with "-b ac3-fix" same problem, + cache...
plugin log: http://pastebin.com/raw.php?i=1SWwjFFh
kodi log: http://pastebin.com/raw.php?i=Umwfa05D

Thanks.

**Comment by pipelka** [comment] 2015-03-19 12:41
It seems these channels announce the audiotracks as AC3 in the PAT/PMT and transmit EAC-3 audio data. This means I have to re-add the ugly hack to handle these situations. I splitted AC3/EAC3 handling some time ago.
Ok. At least I know about the problem now, ...

**Comment by zz64** [comment] 2015-03-19 13:41
I forgot to tell you that I am currently in vdr 2.2.0, do you think it's because of that?
believe me I not had this problem with my old settings (xbmc13.x and old xvdr) with same channels...
is compatibility from vdr 2.2.0 with "helix vdr" related ?
Thanks.

**Comment by pipelka** [comment] 2015-03-19 19:12
Hmm. Don't know. I still have to update to vdr 2.2.
Will check, ...

**Comment by pipelka** [comment] 2015-03-19 19:51
Please repull the "ac-3" branch. Maybe you may find some differences in behaviour.

**Comment by pipelka** [comment] 2015-03-22 05:28
Please recheck with the "ac3-fix" branch. It should work.

**Comment by pipelka** [comment] 2015-03-25 18:21
The following changes have been merged:
pipelka/vdr-plugin-xvdr@43fe18da7ed440b7807d5bb06929e456e9ed8bbd
pipelka/vdr-plugin-xvdr@bf7f671a3fdd9493c46c749587ee3df677545912

I consider this issue fixed with these changes. If not, let me know.

**Closed by pipelka** 2015-03-25 18:21 UTC

**Comment by zz64** [comment] 2015-03-27 15:07
tested (master) today, i confirm that work fine :+1: 
Thanks.

**Comment by pipelka** [comment] 2015-03-27 17:34
Great. Thanks.
